server:
  servlet:
    context-path: /resume-generator
  port: 8080
  shutdown:
    graceful: true
  error:
    include-message: always

spring:
  data:
    mongodb:
      uri: mongodb://localhost/test
      database: resumeGeneratorDB